=== denisbobovnik/Mojster-D.O.O.-/Naloga1spletnaTRGbootstrap/WebContent/XML/shema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="mojsterdoo.si" xmlns="mojsterdoo.si"
	elementFormDefault="qualified">


	<xs:element name="seznamUporabnikov">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="uporabnik" type="uporabnikType"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="uporabnikType">
		<xs:sequence>
			<xs:element name="ime" type="xs:string"></xs:element>
			<xs:element name="priimek" type="xs:string"></xs:element>
			<xs:element name="spol" type="xs:string"></xs:element>
			<xs:element name="enaslov" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="najProdukt" type="xs:string" />
	</xs:complexType>
</xs:schema>

=== denisbobovnik/Mojster-D.O.O.-/Naloga1spletnaTRG/WebContent/XML/uporabnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="trans.xsl"?>
<seznamUporabnikov
	xmlns="mojaTrgovina.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="mojaTrgovina.com shema.xsd" 

>
	
	
	<uporabnik id="u1" najProdukt="p1">
		<ime>Martina</ime>
		<priimek>Štelcer</priimek>
		<spol>Ž</spol>
		<enaslov>joze.kos@email.si</enaslov>
	</uporabnik>
	<uporabnik id="u2" najProdukt="p2">
		<ime>Jas</ime>
		<priimek>Lokić</priimek>
		<spol>M</spol>
		<enaslov>mstelcer@outlook.com</enaslov>
	</uporabnik>
	<uporabnik id="u3" najProdukt="p2">
		<ime>Klara</ime>
		<priimek>Beklašić</priimek>
		<spol>Ž</spol>
		<enaslov>lokicjas@hotmail.com</enaslov>
	</uporabnik>
	<uporabnik id="u4" najProdukt="p1">
		<ime>Žan</ime>
		<priimek>Breznik</priimek>
		<spol>M</spol>
		<enaslov>bekla420@windowslive.co.uk</enaslov>
	</uporabnik>
	<uporabnik id="u5">
		<ime>Jože</ime>
		<priimek>Kos</priimek>
		<spol>M</spol>
		<enaslov>podpora@mojster-doo.si</enaslov>
	</uporabnik>
	
</seznamUporabnikov>
